### ISSUE TITLE
failed to install easystats packages

### ISSUE THREAD

**Issue by kabasele-Theophile** [easystats/easystats#102]
I hope you are well. 
I contacted you because I failed to install easystats packages in Rstudio. I tried the code below but I have a error message. 
code: 
```r
install.packages("devtools")
library(devtools)
devtools::install_github("easystats/easystats")
library("easystats")
```

and 

```r
install.packages("remotes")
remotes::install_github("easystats/easystats")
error message :

> devtools::install_github("easystats/easystats")
Erreur : Failed to install 'easystats' from GitHub:
  Timeout was reached: [api.github.com] Connection timed out after 10004 milliseconds
```

Can you please help me?

**Comment by IndrajeetPatil** [comment]
There is nothing here we can do actually. Your connection timed out. You can try again and it might work.

If you reach the API limit for GitHub, please have a look at this thread:
https://github.com/r-lib/remotes/issues/210#issuecomment-430643547

**Comment by DominiqueMakowski** [comment]
@kabasele-Theophile to complete the previous answer, it seems like your issue is not caused to easystats but to the connection to GitHub from where it tries to download the packages (maybe the website was down for a moment, or maybe too much traffic it's hard to say). A workaround is to install all packages from CRAN `install.packages(c("insight", "bayestestR", "parameters", "performance", "effectsize", "correlation", "modelbased))`, and load them separately. You can then use all the easystats functions as per normal.

**Comment by kabasele-Theophile** [comment]
Thank you for your answer dear Dominique. 
The script you send me worked. 
I can now use the packages. 
thank you
