### ISSUE TITLE
Package for contrasts and means estimations

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#13]
Doing some data analysis for my job, I realised that one of the last aspect lacking to the easyverse (at least for my use) is a brick that handles means, contrasts (and predictions in general), similar to emmeans, ggeffects and the get_predicted/get_means/get_contrasts methods from psycho, but in a more *easy*' fashion.

I will think about a possible design

**Comment by DominiqueMakowski** [comment]
In general, aside from this and a visualisation-oriented package, I currently cannot see any more fields to fill up... which is good, as it means that easystats is getting closer to being scope-complete ☺️

**Comment by DominiqueMakowski** [comment]
Well I've refactored some code that I've already written here and there, and so it came together quicker than expected! [here](https://github.com/easystats/estimate)'s a concept design and syntax, currently only for rstanarm models. Let me know what you think!

**Comment by strengejacke** [comment]
ggeffects would have been a package that fits nicely into the easyverse (and it's really easy to handle). I could of course move the package into the easystats-repo, but I think it's too late for a re-implementation now, since there's an associated publication, and ggeffects has been cited already in quite a lot of different papers now, and has a substantial user base... But in general, a package that _easily_ creates contrasts etc. would be nice. I have also recently drafted a function that computes contrasts in ggeffects. The goal is to include this into plots, i.e. having different line/dot/whatever styles depending on if there's a significant difference between groups.

Three more set of functions come into my mind, which could be included in easystats as well, maybe in existing packages:

- Weighted statistics (see https://strengejacke.github.io/sjstats/reference/wtd_sd.html), because these functions are not readily available in R
- Reliability tests (see https://strengejacke.github.io/sjstats/reference/reliab_test.html)
- Measures of association (https://strengejacke.github.io/sjstats/reference/xtab_statistics.html)

**Comment by DominiqueMakowski** [comment]
Hum yeah, I also think for that it would be better for you to keep ggeffects under you, as it is indeed already very used and useful :) At the same time, I think that the current test implementation (in `estimate` [provisional name]) makes it a different and relatively non-competing package to ggefffects (aside from some of the inherently overlapping methods)? What do you think? 

For other easystats applications, for reliability tests: This could maybe fit into performance? Or having a separate package for *questionnaire data* along with measures of association? 

For weighted stats, I don't see how well it could fit into existing package for now... but it would be a nice feature ot have it. On a side note, I have a very novice question: I am more and more thinking about how to propagate uncertainty into further analysis, for instance the uncertainty related to a participant's level (mean) of X (reflected by the SD) into subsequent correlations or regressions. But I didnt found an easy and consistent way of doing it. Can such weighted statistics be used for this sort of uncertainty propagation?

**Comment by strengejacke** [comment]
1) I think _estimate_ has it's place in the easyverse, let's see in which direction it develops.
2) Maybe _performance_ is indeed a good place for those measures. I would skip Cramer and Phi for now - I still need some functions left for _sjstats_ ;-)
3) Maybe we should skip this for now as well.

>  Can such weighted statistics be used for this sort of uncertainty propagation?

I'm not sure I fully understand your point, but from my first impression, I would say that the weighted-stuff is probably not meeting your needs here...

**Comment by strengejacke** [comment]
Just saw that _performance_ is currently focusing on **model** performance. Should we still include reliability tests then, and enhance the focus, not limited to models?

**Comment by DominiqueMakowski** [comment]
So might say it depends on the definition of a model 😀 (some argue that data is already a model of the world)

The name "performance" is quite agnostic as to its object, so I guess it would not be a drastic or counterintuitive change to increase its focus

**Comment by DominiqueMakowski** [comment]
Also, thinking of it, what could lack is a nice small package for simulations, something "generate some data suited for a binomial model of effect size X and sample size N" :)
