### ISSUE TITLE
ggeffects as part of easystats?

### ISSUE THREAD

**Issue by strengejacke** [easystats/easystats#15]
@DominiqueMakowski 
I'm not sure, but I thought that _ggeffects_ might fit into the easystats-philosophy, though it's a "closed" package including both computation and plotting / printing... But: it aims at easily getting marginal effects, and meanwhile has also reduced package dependencies to a minimum, thus it's rather light-weight...

I'm a bit undecided, and in no way offended it you would opt against having ggeffects here...

**Comment by DominiqueMakowski** [comment]
Tough decision. 

It would be a great "gift" to easystats (in the sense that the benefits would mostly go from ggeffects to easystats rather than the contrary, as it is a well-recognized package already). The easystats ecosystem might definitely benefit from having this star package.

The only thing that you might see me rumbling about is all the argument names, which are quite different from the other easystats packages ^^... And changing them seems quite a harsh and unnecessary change for the users that got used to it...

(Moreover, ggeffects already has a cool logo, it would be a shame to put a monster on it :)

The decision is ultimately up to you, but I am not sure ggeffects has a lot to win from this change (and maybe more to lose from breaking changes, and loss of google visibility due to URL changes). The greedy "I" would say "**yes bring it over so it can shine a bit on me**" but at the same time, to be honest, I feel like it is good to have (at least) one "successful" package directly attached to you for... you know, github fame and all 😅 


As I am thinking about this, an alternative win-win way could be leaving everything "as is" for now, and loose-affiliating ggeffects to easystats. For instance, we could put on its readme page "this package is a part of the easystats suite". At the same time, we would advertise ggeffects in easystats' blogposts, docs, tweets and such as if it was one of his own, increasing the visibility of both. And in the future, if easystats is a big hit, we can re-think about hard-including ggeffects in it.

**Comment by strengejacke** [comment]
I'm not aiming at more visibility for _ggeffects_, but rather _easystats_ would probably benefit from ggeffect's current dissemination.. But I agree, it's more a "foreign body" in the easyverse, and not "grown" package (it's more like a artificial city district, that has not evolved in the course of time...).

I agree, maybe we should wait and see if there's some point in the future where we say that ggeffects would fit into and add to the easystats-portfolio.

**Comment by DominiqueMakowski** [comment]
Yes, that's why the greedy me would be very keen on having it there 😀 

but yes, it won't hurt waiting a bit just to see where easystats is headed, in particular with its plotting abilities #14... you know, if we start having a visual "style" you might prefer having your personal ggeffects/sjsverse style separate from the easysverse one :)

But anyway, I am all in for advertising ggeffects as if it was part of the family!

**Comment by strengejacke** [comment]
I wasn't thinking of any advertising in the first place, but indeed from a user's perspective to have a "comprehensive" portfolio of useful packages to easily do stats with R - and since we have a strong focus on modelling, ggeffects wouldn't be far away from this philosophy ;-) (despite based on a slightly different design-philosophy/ argument-style). But let's see how _estimate_ is developing, maybe that one is meeting the (users') needs already.
