### ISSUE TITLE
add *tinyverse* badges to `README`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#183]
Like so (h/t @vincentarelbundock):
https://github.com/easystats/parameters/blob/dba37f5ffcaa8bd9c4bce52f7ad238bf4d5208f4/README.Rmd#L36

Progress:
- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [ ] see
- [x] datawizard
- [ ] easystats (will have to wait CRAN submission)

**Comment by mattansb** [comment]
Not all pkgs are very tiny - e.g., `effectsize`: ![](https://tinyverse.netlify.com/badge/effectsize), `see`: ![](https://tinyverse.netlify.com/badge/see)...

**Comment by IndrajeetPatil** [comment]
That's fine. 

5 or 8 is nothing compared to what a typical package that relies on any of the `{tidyverse}` packages has (most of 35 for `{see}` are coming via `{ggplot2}`).

**Comment by IndrajeetPatil** [comment]
I think this should suffice. It won't be appropriate to have this badge for `{see}`.

**Comment by vincentarelbundock** [comment]
Thanks for these @IndrajeetPatil !

I like those badges a lot and tweet with network graphs too! Most of all, I like that "no dependencies" is a key part of the `easystats` "identity".

**Comment by IndrajeetPatil** [comment]
Are you also considering downsizing the dependencies of `{modelsummary}` in the future? 

I am curious why you simultaneously rely on both broom and easystats ecosystems. Is it to maximize the model coverage?

![image](https://user-images.githubusercontent.com/11330453/140662506-9b6363fa-d729-4dd1-9836-9a49e9c58ca0.png)

**Comment by vincentarelbundock** [comment]
It's egregious, isn't it? (Especially when the picture is sooo big on Github ;))

In this case, it's really hard to get rid of the dependencies, because they almost all come along with the main culprit: `kableExtra` the table drawing package. That package imports nearly all the `tidyverse`, `rmarkdown`, some SVG stuff and `viridisLite`, `digest`, and a bunch of others.

Removing `broom` would make essentially no difference, because all the packages that `broom` imports are also imported by `kableExtra`.

Aside from that, we have:

* `rlang`: Could remove this at almost no cost. Has 0 dependency itself.
* `checkmate`: Could remove this but I use it extensively to check user input. Has 0 dependency itself.
* `glue`: Required for key functionality. Has 0 dependency itself.
* `tables`: Required for all the `datasummary_*` family of functions
* `parameters`, `performance`, `insight`

**Comment by vincentarelbundock** [comment]
> I am curious why you simultaneously rely on both broom and easystats ecosystems. Is it to maximize the model coverage?

For users who want to customize to add support for new models or customize objects, I think that the `broom` S3 classes super easy to work with.  The docs make extensive use of them: https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#adding-new-models-part-i-

I could potentially get rid of `broom` and substitute with `generics`. But the statistics produced by `glance` and `performance` are slightly different, and I would have to re-write dozens of tests if I switched to `performance` by default.

**Comment by IndrajeetPatil** [comment]
Ah, yes, that makes sense then. 

Thanks for the detailed explanation! Was just curious to know why, since if it was because of some models which are not covered in `{easystats}`, that might be easier to resolve. But the issues you mention are much more difficult and time-consuming to deal with.

I was in a similar situation a couple of years ago when I started to move from `{broom}` to (then nascent) `{easystats}`, and it took a LOOOONG time to make this transition. But I am a happy customer now, every `{easystats}` update breaking my packages notwithstanding! 😅

**Comment by strengejacke** [comment]
At least, the _parameters_ API was simplified so now it's mostly a matter of the correct `degrees_of_freedom()` method. `standard_error.default()` relies on `vcov()` if not possible to extract SEs from the summary, and `p_value()` and `ci()` just need the DF then. But true, extending _broom_ is still a lot easier than adding new models to _easystats_.

**Comment by vincentarelbundock** [comment]
> At least, the _parameters_ API was simplified

Oh yeah, and it is *entirely* satisfactory for my needs. In most cases, we get *more* stuff with `parameter`, so the only issue is that most of my early tests are hard-coded tables with a smaller list of statistics, so they would look different (bigger) if I removed `broom`. So it's really laziness at this point ;)

**Comment by bwiernik** [comment]
Maybe something we can help with at some point as time goes on

**Comment by bwiernik** [comment]
What does the dependency situation look like for *gt*

**Comment by vincentarelbundock** [comment]
> Maybe something we can help with at some point as time goes on

Cool. Really, we just have to think about whether it's worth the person-hours. If it allows me to get rid of only one (recursive) dependency, I'm not sure it's worth it. But I'll think about it and investigate a bit.

> What does the dependency situation look like for gt

`gt` is all-in on the `tidyverse`, so it's pretty much the same in terms of dependencies. The first few versions of `modelsummary` actually had `gt` as default, but I switched to `kableExtra` because `gt`'s LaTeX support was terrible (and thus Rmarkdown PDF and all related formats). Things might have improved since then, but `kableExtra` has some nice features and a more concise syntax, so I don't feel the urge to switch away.

**Comment by strengejacke** [comment]
But I don't think that _modelsummary_ is a package that needs to be very lightweight, anyway. The target audience are users, not developers, or not?

**Comment by vincentarelbundock** [comment]
> But I don't think that _modelsummary_ is a package that needs to be very lightweight, anyway. The target audience are users, not developers, or not?

Yeah, that's probably right. Although I will say that even as a user, dependencies can bite hard sometimes. For instance, I have old projects on my computer that can't replicate because one of the dependencies is no longer installable straight from CRAN.

When I start new projects nowadays, I use `renv` to keep track of the exact dependencies and to make sure that the results are 100% replicable. When doing that, I actually exclude `modelsummary` from tracking, and rationalize this by saying that drawing the tables is mostly a "cosmetic" step and that all the raw results are available and replicable with a very small set of packages.

I'm trying to publish a JSS article about `modelsummary`, and here's how I address the issue:

> \pkg{modelsummary} has two main drawbacks. Since the package does not draw tables itself, users sometimes need to call external functions to change the appearance of their outputs. For deep customization, many analysts will thus choose to learn an external package like \pkg{kableExtra} or \pkg{gt}. Relatedly, \pkg{modelsummary} requires dependencies to extract model results and draw tables. Those dependencies do not pose a serious threat to the future of the package because they are actively-maintained, have large user-bases, and because \pkg{modelsummary}'s modular design would allow its developers to pivot easily if one upstream package were deprecated. Nevertheless, users who do not want to onboard too many dependencies may want to consider alternative packages.
