### ISSUE TITLE
Update to `v2` of GHA

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#200]
A lot of minor and major improvements from `v1`. Just copy files from here:

https://github.com/r-lib/actions/tree/v2-branch/examples

Progress tracker:

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by etiennebacher** [comment]
In addition to switching to v2, maybe actions should be harmonized between repos? For example [insight](https://github.com/easystats/insight/blob/master/.github/workflows/R-check.yaml) and [datawizard](https://github.com/easystats/datawizard/blob/master/.github/workflows/R-check.yaml) have quite different configs. I wonder if it's possible to have an `easystats-actions` repo that contains a single yaml file, and then each repo calls this file.

Also, some of these repos have an action for macos-latest with R-devel, which fails when the action is not v2 (see https://github.com/easystats/insight/runs/6721433287?check_suite_focus=true for instance). Switching to v2 will get all the deps for macos-latest with R-devel the first time it is run, and this takes time (almost 3h) because binaries are [not available yet ](https://github.com/r-lib/actions/issues/546#issuecomment-1084250545). However, I think deps are cached after the first run and macos-latest with R-devel runs correctly (see a test [here](https://github.com/etiennebacher/parameters/runs/6722027784?check_suite_focus=true)).

**Comment by mattansb** [comment]
The new streamlined GHA does not check on older versions of R - which I think it should, given that we claim to support these (currently, we support as back as R 3.4).

**Comment by IndrajeetPatil** [comment]
This is a bit of a nightmare since we include tons of packages in `Suggests`, and a lot of them support only R versions > 3.6, > 3.5, or > 3.4. This means that we need to go through all dependencies and their recursive dependencies and figure out installation of which packages need to be skipped before which R version.

So we end up something like [this](https://github.com/easystats/correlation/blob/master/.github/workflows/R-check.yaml):

```yaml
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            energy=?ignore
            Hmisc=?ignore-before-r=3.6.0
            poorman=?ignore-before-r=3.5.0
            BayesFactor=?ignore-before-r=3.5.0
            polycor=?ignore-before-r=3.5.0
            rstanarm=?ignore-before-r=3.5.0
            WRS2=?ignore-before-r=3.5.0
          needs: check
```

This *might* get easier if we successfully implement #234, since in that case all such specifications can be made only in one place.

**Comment by mattansb** [comment]
> This means that we need to go through all dependencies and their recursive dependencies and figure out installation of which packages need to be skipped before which R version.

Why would we need to do this?
All tests should be conditional on the needed packages being installed. So worst case, we get a "skipped" from `testthat::skip_if_not_installed()`.

**Comment by IndrajeetPatil** [comment]
Skipping tests happen during R CMD Check phase (`actions/check-r-package`) of the github action, while the builds fail even before then - while downloading needed dependencies (`actions/setup-r-dependencies`). 

This is why skipping them won't be of help.

**Comment by mattansb** [comment]
Oh, that sucks..................

**Comment by mattansb** [comment]
But... If that is the case, why weren't R-Check failing in `effectsize` for older versions of R? I didn't have any `emmeans=?ignore-before-r=3.5.0` or anything like that...

**Comment by IndrajeetPatil** [comment]
Because, before you were using `actions@v1`, which had a different logic to how it was downloading dependencies. This problem is happening because of `actions@v2`, which are worth this trouble.

**Comment by mattansb** [comment]
Ah, but it actually sounds like it's adding more work!

**Comment by IndrajeetPatil** [comment]
I think it's worth it since the workflows are fairly cleaner. And it's a one-time investment that will pay off for a long time.

**Comment by IndrajeetPatil** [comment]
Even _tidyverse_ doesn't test on `R 3.4` (e.g. [ggplot2](https://github.com/tidyverse/ggplot2/blob/main/.github/workflows/R-CMD-check.yaml)). The oldest R version they test is `R 3.5.3`.

**Comment by etiennebacher** [comment]
I supposed this can be closed now
