### ISSUE TITLE
Citeable easystats

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/easystats#24]
I've received questions about what's the right way to cite the package(s).

One "guidelines" option would be to recommend citing the particular package used + general easystats citation. For instance citing insight + easystats, or bayestestR + easystats etc.

Unfortunately, we are currently nowhere near having something ready for the general easystats citation, which will be possible once we have released most of the core packages. 

However, we could maybe consider drafting a very small and preliminary preprint for easystats (presenting the general aim and packages), which might immediately start to be cited. Then, we would improve this preprint until we submit it to a journal. Hopefully, the citations would transfer to the published version.

**Comment by strengejacke** [comment]
I've read some recommendations from GitHub-people, that I think are quite useful. In short, it's recommended those packages that either directly lead to visual output used in a paper, or where inferences / results are based on. Hence, I would actually never cite _insight_.

**Comment by DominiqueMakowski** [comment]
Although it could still happen in some technical publications where the way of extracting stuff is of importance?

But nonetheless, the point still holds for the other packages, which for most of them return some actual results

**Comment by strengejacke** [comment]
yes, performance, bayestester (and parameters), to name current packages, are all citeable. _easystats_ as a project probably not.

Would you suggest a "generic" citation, or `citation(<packagename>)`?

**Comment by strengejacke** [comment]
> very small and preliminary preprint 

That seems to be a good idea, actually!

**Comment by DominiqueMakowski** [comment]
I am just saying that one day, I think the project itself could be worthy of publishing, providing the general overview of features and scope. Because all of the packages can be seen independently or with the bigger picture. Hence, it would make sense for users to cite the *specific* packages as well as the general project-one. A temporary citeable material could be a preprint... well based on your updated comments, you got what I meant :)

**Comment by humanfactors** [comment]
The overall easystats framework could have a paper, but I think that each package should have it's own DOI as well. I just wanted to throw one option out there that hasn't been raised, and that is actually generating a DOI for the Github releases themselves ([through Zenodo](https://guides.github.com/activities/citable-code/)). There's obviously some further considerations to be made here, but I personally find it more intuitive to cite a specific package than the paper accompanying it.

**Comment by DominiqueMakowski** [comment]
I believe our plan is indeed to "publish" each package separately, in specialized software journals, with a DOI and a journal reference. So they will be all fully citeable, hopefully in a not-too-distant future :) 

One of the practical reason for a big meta-paper for easystats is also to mitigate for the hierarchical structure of the packages. People indeed tend do cite high-level packages, that allowed them to perform the analysis or get the results. In this context, we expect packages like for instance `report` to be more cited that a low-level package such as `insight`. Which is kind of unfair, since without insight none of the packages would even exist. Also, on a more abstract level, all these packages were thought from the start as being components of this one ecosystem. 

The way I see it, for each package's citation recommendation ("how to cite" section), we could add two citations, the one specific to the package and the general easystats one. This way, people would credit the specific tools, but also the big picture idea that allowed these tools. Moreover, I feel like this is in line with the open and collaborative spirit of the project to have one big reference to credit everybody :)

**Comment by DominiqueMakowski** [comment]
🚨 to all easymembers this is not a drill I repeat this is not a drill 🚨 

And here we are, a few months after this discussion. Crazy as time flies. Anyway, long story short, I think that the project's pragmatic "success" (as measured by the feedback of friends after giving them a fiver 💰) has outdistanced its academic visibility. We have created some non-yet citeable material (all the packages but insight and bayestestR), so it'd be good to address that. 

Of course, the best alternative would be to deliver the remaining packages to a stable state and publish them... but "ain't nobody got time for dat" (yet). A faster temporary fix would be thus to write a small piece presenting the project as a whole and providing an overview of the scope and content, which could be preprintable and hopefully submitted somewhere.

This could be the occasion for all of us to collaborate on it by writing a paragraph for this or something (and this way we could all also benefit from the citeability and publication of the project as a whole).

I created an initial outline available here: https://github.com/easystats/easystats/tree/master/publications/makowski_2020_easystats

The paper is written in Rmarkdown using [papaja](https://github.com/crsh/papaja). The current authorship includes me and @strengejacke, but the rest has yet to be decided (a contribution-basis seems fair?). I'd love to see all of you on it ☺️

Without any further ado, let's open the discussion about this and share ideas, opinions, thoughts and suggestions. And do make direct PRs to the paper!

@pdwaggoner @mattansb @IndrajeetPatil @humanfactors @jacob-long @lindeloev 

PS: I know this is a busy time for all of us employed people, and we never have as much time as we'd like for such cool projects (right?). Although even the tiniest contributions are encouraged, please do not cancel any parties or romantic dinners for that ;)

**Comment by pdwaggoner** [comment]
Hi @DominiqueMakowski - I think this is a great idea! My only question is where you think a likely journal target might be? I only ask because most software journals require pretty streamlined and short communication, I guess with J Stat Soft being an exception in certain cases. So are you envisioning a meta, longer paper to J Stat Soft, or even the R journal? This might influence the depth we go into on each package, given the current outline.

And for what it's worth, I would be happy to draft the section on `insight` given our previous paper on that package. I could contribute to `see` and `performance` as well, if needed. 

Just getting ducks in a row prior to contributing. Thanks again for suggesting this and for the open invitation to contribute!

**Comment by DominiqueMakowski** [comment]
No idea where to submit such a manuscript... although I agree that this would influence the depth and amount of work needed. I wonder whether it is more adapted to a software journal (as it is not a software *per se* but rather an introduction to an ecosystem) or a more general paper, as some sort of tutorial or presentation 🤔 J Stat Soft could be a possibility, but I wonder if it would fit with their scope

**Comment by humanfactors** [comment]
Something that might assist us in better deciding the target journal and audience is really thinking through (1) what would be most useful to a reader, and (2) what would attract more usage to the ecosystem. I'm not sure we need a full tutorial (as we have vignettes), but I think showing some example use cases (particularly with Stan) would be instrumental in conveying the utility of the ecosystem. It would be crucial however to explain what each package does, **and how they fit together**. This latter point is important to make clear upfront, because I think it can be overwhelming seeing the number of packages (given they are all quite inter-related).

I don't really think our work is in the scope of J Stat Soft, which typically concentrates on packages that specifically enable or facilitate new statistical methodologies. Moreover, the journal reviewing process is stringent and can be quite long (or so I've read), see [[1]](https://ntguardian.wordpress.com/2018/08/05/time-to-accept-it-publishing-in-the-journal-of-statistical-software/)[[2]](https://robjhyndman.com/hyndsight/jss-rpackages/). This is obviously a serious limitation if we are aiming to get it out as fast as possible.

The R Journal seems like a candidate, though I will be honest I know little about the requirements and review process there. A limitation might be that all packages may need to be on CRAN to be accepted.  Journal of Open Source Software is another viable alternative that you've had experience with.

I'll continue to think, but I do think it's worthwhile us working out the target before we dive too deep into writing (as framing could change substantially).

**Comment by IndrajeetPatil** [comment]
I agree with @DominiqueMakowski that we can probably work on a short paper for the entire `easystats` project itself. A good reference point for this is the `tidyverse` paper: https://github.com/tidyverse/tidyverse/blob/master/vignettes/paper.Rmd

As for the venue for publishing this, I would vote for _JOSS_, but will also be happy with other Open Access solutions.

**Comment by pdwaggoner** [comment]
@IndrajeetPatil good suggestion - I like that as a general template. I agree open access would be the way to go. We have done a bit at JOSS, so this is a clear candidate. We could also consider something from this list: https://www.software.ac.uk/which-journals-should-i-publish-my-software 

Might be a helpful thing to get us started in thinking of an appropriate outlet.

**Comment by DominiqueMakowski** [comment]
Here's also the small list put together for report (with metrics)

**Comment by jacob-long** [comment]
If we want to do something a bit more longform than JOSS, the R Journal would be worth consideration, I think. I've not heard much about the review process, but I suspect it's not as long/arduous as Journal of Statistical Software (where I agree this is not a great fit, anyway).

**Comment by lindeloev** [comment]
I don't know how I missed this thread, but it's a great idea!

I'm late to the game so this is almost an outsider's view. One general message could be that you change habits by making things *easier*, including *more attractive*, than the alternatives. And easystats makes it easier to *do the right thing*. I know this is a psychological take on a stats paper, but exemplifying that easystats achieves this goal could be more journal-like. JOSS would be a great outlet for that.

I could draft something about this "take".

**Comment by DominiqueMakowski** [comment]
tidyverse just got a new global ref: https://joss.theoj.org/papers/10.21105/joss.01686

we could use this for inspiration

**Comment by strengejacke** [comment]
_bump_

Not sure how, but I think we can indeed add some text to your draft and submit a preprint... I think it's indeed useful if people use 3 or more packages of the easystats-project, to avoid citing too many papers.

**Comment by strengejacke** [comment]
we need to update the CITATION file in this package as well...

**Comment by IndrajeetPatil** [comment]
Yeah, I like this idea. People might indeed skip on citing individual packages if they think there are just too many of them to cite. 

The `tidyverse` ecosystem also has just a single citation: https://github.com/tidyverse/tidyverse/blob/master/inst/CITATION

**Comment by IndrajeetPatil** [comment]
Let's make this new year's goal! 😅

**Comment by DominiqueMakowski** [comment]
This year goals are report on CRAN, publish performance, and then finally this ☺️ 🚀

**Comment by IndrajeetPatil** [comment]
Closing in favor of #131
