### ISSUE TITLE
Bump minimum needed R version to `R 3.6`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#304]
As decided [here](https://github.com/easystats/easystats/issues/295).

There are two tasks here:

- Bump version in `DESCRIPTION`.
- Remove all backports or conditional logic that relies on the assumption that we support R versions older than `3.6`.
- Update `NEWS.md` to mention this breaking change.

# Progress tracker:

- [ ] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by strengejacke** [comment]
Maybe we should still support R 3.5 for _insight_? There are several prominent packages that import _insight_ and themselves rely on R 3.5...

**Comment by IndrajeetPatil** [comment]
Can't they also bump to `R 3.6`? 
At any rate, this shouldn't create troubles for them, since CRAN doesn't check on these older versions. Their users would need to upgrade to `R 3.6`. And, after 2 and half years, maybe it's about time?

I'd prefer the entire ecosystem to be in sync in terms of supported R versions. This is where a written policy (#295) would help us; we won't have to explain ourselves to anyone. 

We shouldn't support R versions older than 2 years, TBH. In the fast-paced world of software development, 2 years is an aeon, and even in the slow and restrictive world of clinical trials - where they are the most resistant in terms of upgrading to newer R versions - it's a while. 

I don't like supporting older R versions just for the sake of supporting them, especially when our CI/CD workflow no longer checks for these R versions.

**Comment by strengejacke** [comment]
> This is where a written policy

But tidyverse packages support back R 3.1 or maybe even older. @vincentarelbundock what do you think? Some of your packages are affected, too.

**Comment by strengejacke** [comment]
> I don't like supporting older R versions just for the sake of supporting them, especially when our CI/CD workflow no longer checks for these R versions.

I agree, but I remember we once switched to R 3.6 and then back to R 3.4 because this caused troubles (i.e. user reported issues) in other packages because they didn't work for older R versions.

**Comment by IndrajeetPatil** [comment]
> But tidyverse packages support back R 3.1 or maybe even older.

Again, they _say_ they support all those older versions, but their CI/CD checks only until `oldrel-4` (`R 3.5`). 
How do you know it works on (e.g.) `R 3.2` if it's not being tested either by CRAN or by CI workflows?

**Comment by IndrajeetPatil** [comment]
> I agree, but I remember we once switched to R 3.6 and then back to R 3.4 because this caused troubles (i.e. user reported issues) in other packages because they didn't work for older R versions.

I don't remember this, but maybe `R 3.6` was that old back then, and so maybe some packages were not prepared for it?

**Comment by IndrajeetPatil** [comment]
For reference, `R 3.6` was released on `2019-04-26`.  Over 3 and half years is enough time to for users to have upgraded to this version.

I don't know why we are having this discussion, @strengejacke, if you were going to revert this change in _insight_ anyway.

**Comment by strengejacke** [comment]
I tried to move the commits into a new PR to have the changes on hold, but didn't succeed (if this is possible at all?). But I didn't want to have these changes in main right now, until we're sure that there's no objection from other maintainers, mainly @vincentarelbundock who might post here, because I feared commits will be messed up when there are commits added afterwards?

**Comment by strengejacke** [comment]
Not sure if we could revert these commits after new commits were added?

**Comment by IndrajeetPatil** [comment]
It's fine. Shouldn't be too hard to recreate that commit.

**Comment by IndrajeetPatil** [comment]
Results from an informal poll on

- Twitter

<img width="597" alt="Screenshot 2022-09-17 at 11 29 34" src="https://user-images.githubusercontent.com/11330453/190850191-baa0fb0c-a71e-4f7d-ae18-3c94c8c5a329.png">

- LinkedIn

<img width="531" alt="Screenshot 2022-09-17 at 11 31 07" src="https://user-images.githubusercontent.com/11330453/190850199-906c2984-ebf3-4321-b98d-0871e5f2413e.png">

R < 3.6 is definitely a rare occurrence.

**Comment by vincentarelbundock** [comment]
Sorry, I missed this discussion.

My view is that 2 years is very short, and I would hope to support software for longer. Some computer clusters still run old versions. And 3% of users can still be A LOT of people.

Do we need specific functionality from post-3.5 that isn't available in ˋbackports`? I think the driving force should be functionality and not continuous integration, where it is pretty easy to selectively skip tests or adjust them.

Sorry to contradict!!

**Comment by IndrajeetPatil** [comment]
`R 3.6` was 3 and half years ago, so the policy can specify that period.

**Comment by vincentarelbundock** [comment]
Yeah, if easystats has 10s of thousands of users -- quite likely-- cutting support for pre-3.6 (5% of Twitter poll) means a major inconvenience to 100s (1000s?) of people.

I think we would need *excellent* reasons to do this.

**Comment by strengejacke** [comment]
I'm a bit torn. Personally, I would say version 3.6 is enough. And indeed, we don't check if our packages run on version 3.5. On the other hand: I think they work on R 3.5 as far as possible, and since _insight_ is used by many other packages, even more "famous" ones, that still support 3.5, what is the extra cost to continue supporting 3.5 ourselves?

N.B.: If we would drop 5% of users, I would start with Mac users ;-)

**Comment by strengejacke** [comment]
And a technical issue: There is the possibility to create a new branch from a commit, but this didn't work, as it's on par with main, and I couldn't create a PR. :-/ Else, I would have tried to move the commits to a PR, because I feared adding more commits to main afterwards would make it more difficult to revert the commits that changed min. requirement to 3.6 - but maybe one can just revert any commit at any point?

**Comment by strengejacke** [comment]
> Do we need specific functionality from post-3.5 that isn't available in ˋbackports`?

We don't use _backports_, we have our own internal implementation of `str2lang()`. The main point is a) we don't test our packages on R 3.5, and b) there are indeed _many_ packages that obviously don't care and even require R 4.0 or higher.

**Comment by vincentarelbundock** [comment]
Hehe

What's the case for stopping support? Sure, we can run the tests on GitHub, but as long as we don't use more modern functions things should work in principle (as you said). And keeping them is ~0 work for us. Sometimes I miss ˋisFALSEˋ but that's not a big deal.

It just feel line the negative case is clear (1000s of people inconvenienced) while the positive case has not really been made (or I missed it).

**Comment by strengejacke** [comment]
I think `isFALSE` is already in 3.5, we needed it only when we supported R 3.4.

**Comment by IndrajeetPatil** [comment]
I am personally fine with cutting them off. I am pretty sure there are clusters and users still stuck on R 3.4, and we have already cut them off. That's the cost one has to pay for being conservative. 

And don't forget that others packages have already bumped minimum needed R version to 4 (e.g. `foreign`) or even 4.1 (e.g. `emmeans`).

If after over 4 years, someone hasn't upgraded to a newer R version, I doubt they are ever going to. I honestly don't know why people wish to continue to use older, bug-ridden versions of software.

At any rate, @strengejacke is the benevolent dictator for _insight_, so I am fine with whatever he decides.

**Comment by strengejacke** [comment]
![as-benevolent-dictator](https://user-images.githubusercontent.com/26301769/190851650-d0c59f8a-ef0c-4db7-9499-fb9d342251c4.jpg)

**Comment by IndrajeetPatil** [comment]
For the uninitiated:

https://en.m.wikipedia.org/wiki/Benevolent_dictator_for_life

**Comment by vincentarelbundock** [comment]
> a) we don't test our packages on R 3.5, and 

This just means we can't offer strong guarantees, not that we should cut them off entirely.

> b) there are indeed _many_ packages that obviously don't care and even require R 4.0 or higher.

"Infrastructure" packages should be much more conservative than other, IMO.

In any case, this won't keep me awake at night. I just wanted to raise these arguments and am fine with what you decide.

**Comment by strengejacke** [comment]
> I honestly don't know why people wish to continue to use older

I doubt that people _wish_ to do so. There are less experienced users who run R every couple of weeks or months, and never see the need to update, because they're no "computer nerds". In my experience, updating software happens when I ask colleagues to do ;-) And, regarding sampling bias, I would guess that many people who still use R < 3.6 are not on Twitter or LinkedIn. ;-) 

Or some people got R installed by their IT some years ago, and still use it because it "worked" and they didn't want to go through the administrative steps to update their software etc.

But anyway, these are just things to keep in mind, I personally rather prefer push new developments and use newer software versions...

**Comment by strengejacke** [comment]
> https://en.m.wikipedia.org/wiki/Benevolent_dictator_for_life

Someone should add me to that list...

**Comment by strengejacke** [comment]
Maybe we could classify our packages into something like "critical infrastructure" (like _insight_), which should also support R 3.5, and other packages which core functions rely on packages that need newer R versions anyway, and those go back "only" two versions older than r-oldrel? I'm not sure if it's easy to find a good policy here, "consistency" in min. support is also a good argument, imho.

**Comment by bwiernik** [comment]
> Maybe we could classify our packages into something like "critical infrastructure" (like insight), which should also support R 3.5

Those would be insight and datawizard I think

**Comment by bwiernik** [comment]
I know a bunch of people who one of a few researchers in a big company. The IT in those places often doesn't really think about what R users' needs are and tends to install once and then never upgrade.

**Comment by DominiqueMakowski** [comment]
I don't have much to add to the convo, but my experience was with people that also never upgrade "as long as it works" because of fear of stuff breaking or merely just laziness of having to update and reinstall. So I'd say we do them a favour by forcing them to upgrade at some point. TLDR; rather pro >= 3.6

**Comment by IndrajeetPatil** [comment]
`{insight}` stays at `R 3.5` (2018-04-23); everything else moves to `R 3.6` (2019-04-26).

Meanwhile, `R 4.2.2` will be out on 2022-10-31.
