### ISSUE TITLE
Improve conditional vignette evaluation

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#313]
Currently, we conditionally evaluate vignettes; skipping them if any of the required packages are not available. Instead, we need to take a more granular approach by skipping evaluation only of those chunks that need the unavailable packages. 

Daniel has done this for a vignette [here](https://github.com/easystats/parameters/commit/c31b316c0a88e1ff9c8e31fdade97064bf7b4cc2). I think this basic pattern can be utilized in other packages as well. 

# Progress tracker:

- [ ] insight 
- [ ] modelbased
- [ ] bayestestR
- [x] effectsize
- [ ] parameters
- [ ] performance
- [ ] correlation
- [ ] report
- [ ] see
- [ ] datawizard
- [ ] easystats

**Comment by etiennebacher** [comment]
I think it works in the vignette you link to because it's like each chunk is "independent" but it quickly becomes tricky to show a workflow with several packages. For example, if I define `x <- lme4::lmer(something)` and `lme4`  cannot be loaded, then this code will not be evaluated but I also have to prevent evaluation of all following chunks using `x`. 

Also, this means that depending on whether external packages can be loaded, the docs on the website will sometimes show evaluated chunks and sometimes not. It seems to me that it's preferable to skip the evaluation of vignettes entirely.

**Comment by IndrajeetPatil** [comment]
That's a fair point. Yes, definitely. The devil is in the details here. 

I think packages which are required across the entire vignette or across many chunks should be used for skipping evaluation at the top level. Otherwise, they should be used for each chunk.

Let me try to do this for _datawizard_ and _see_ and see if this is too onerous of an ask.

**Comment by strengejacke** [comment]
I made these changes because I wanted to link to this vignette and saw that no outputs were shown, most likely due to a failure of a single package. However, this doesn't mean that we can't show outputs of other code chunks, to have at least _some_ content. That's why I tried to conditionally evaluate code chunks. I agree this might not be the best way for each vignette we have, but maybe we can get back to this issue every now and then...

**Comment by IndrajeetPatil** [comment]
Closing in favour of https://github.com/easystats/easystats/issues/341. 

I don't think we need such finer control over evaluation at this point, since most of the soft dependencies used are stable enough as not to be expected to be archived.
