### ISSUE TITLE
About loading packages in tests

### ISSUE THREAD

**Issue by etiennebacher** [easystats/easystats#363]
We use a lot of external packages in the tests with `library()`, and this sometimes creates issues because these packages load functions and methods that are conflicting with some of our functions, see for instance https://github.com/easystats/datawizard/pull/389. Note that this especially occurs when we run the test files in a random order.

I asked about this in https://github.com/r-lib/testthat/issues/1759, which lead me to [this chapter](https://r-pkgs.org/testing-design.html#sec-testing-design-self-contained) of "R Packages":

> Unnecessary calls to library(somePkg) in test files have a real downside, because they actually change the R landscape. library() alters the search path. This means the circumstances under which you are testing may not necessarily reflect the circumstances under which your package will be used. This makes it easier to create subtle test bugs, which you will have to unravel in the future.

Do we need to change the behavior of `skip_if_not_or_load_if_installed()` (cf https://github.com/easystats/easystats/issues/350) because it calls `library()`?

---

This [SO answer](https://stackoverflow.com/a/75837546/11598948) suggests a different testing framework so it's good to know but not achievable in our case.  

## Progress tracker

- [x] insight 
- [x] modelbased
- [x] bayestestR
- [x] effectsize
- [x] parameters
- [x] performance
- [x] correlation
- [x] report
- [x] see
- [x] datawizard
- [x] easystats

**Comment by etiennebacher** [comment]
Using `::` will probably solve the problem for functions exported by other packages but methods will still be available in the namespace so it won't solve everything (but I'm actually not sure we can do something to solve everything).

Also, this basically means reverting `skip_if_not_or_load_if_installed()` to `skip_if_not_installed()` + `::`. Is there an easy way to revert some commits, even made a few days/weeks ago?

**Comment by IndrajeetPatil** [comment]
I have cleaned up tests in `{see}` to address this issue (https://github.com/easystats/see/pull/280).

**Comment by IndrajeetPatil** [comment]
> Do we need to change the behavior of skip_if_not_or_load_if_installed() (cf https://github.com/easystats/easystats/issues/350) because it calls library()?

Actually, we should just get rid of that helper and just go back `skip_if_not_installed()`. 

Note that #350 was created in a different context. Most of our tests don't use `::` to access functions from soft deps, and also don't explicitly load datasets from soft deps with `data()`, and so it was necessary to use `require()` calls. Additionally, we also wanted to reduce noise in tests due to loading these different packages, and so `skip_if_not_or_load_if_installed()` seemed like a good solution at the time.

If we want to use only `skip_if_not_installed()`, then we need to make sure all used functions are namespaced and datasets are explicitly loaded. That's why I said this is going to be a lot of work.

**Comment by IndrajeetPatil** [comment]
If we absolutely must load some packages in a test file, it's a good idea to unload the namespace at the end of the test file (cf. https://github.com/easystats/parameters/commit/391217545deba2d0c2963e7fdbfecc6ff31cca63).

**Comment by rempsyc** [comment]
I find that using namespacing instead of loading for `rstanarm` does not work most of the time. It's really funky. It tries to call functions that the script is not calling, but cannot find them. Even defining those functions manually result in more errors like:

```
Unable to refit the model with standardized data.
 Try instead to standardize the data (standardize(data)) and refit the
 model manually.
```

So I am loading it for those instances. But  I wonder if someone found a way to make it work with namespacing somehow?

**Comment by etiennebacher** [comment]
Nope, it's not enough:

``` r
library(testthat)

test_that("foo 1", {
  print("as.matrix.get_predicted" %in% methods(as.matrix))
})
#> [1] FALSE
#> ── Skip (???): foo 1 ───────────────────────────────────────────────────────────
#> Reason: empty test

test_that("foo 2", {
  withr::local_package("insight")
})
#> ── Skip (???): foo 2 ───────────────────────────────────────────────────────────
#> Reason: empty test

test_that("foo 3", {
  print("as.matrix.get_predicted" %in% methods(as.matrix))
})
#> [1] TRUE
#> ── Skip (???): foo 3 ───────────────────────────────────────────────────────────
#> Reason: empty test
```
`withr::local_package()` calls `detach()` under the hood, and the docs of `detach()` say:

> If a package has a namespace, detaching it does not by default unload the namespace (and may not even with unload = TRUE)

I think we're doing the best we can about this

**Comment by IndrajeetPatil** [comment]
I think we have done everything we can here and there is not much to do.
