### ISSUE TITLE
Dprime and SDT measures

### ISSUE THREAD

**Issue by marco2gandolfo** [easystats/easystats#78]
Hi all,

Thanks for this very nice set of packages.
I have been still using the "Psycho" package. When I load this in R it says to refer to easystats and to open an issue for a function that cannot be found in easystats.
It would be great to see the d-prime function (which computes several of the Signal Detection Theory measures (dprime, aprime, beta, c... etc) ported here.
Just flagging it, in case there is the interest in porting it here.

Thanks all for the very nice set of resources you are building up.
Cheers,
Marco

**Comment by strengejacke** [comment]
@DominiqueMakowski That's probably something for you to address?

**Comment by DominiqueMakowski** [comment]
Hi @marco2gandolfo thanks for chiming in! Well initially the goal was to remove from psycho all the non-psych stuff (ported in easystats), and to keep there all the psychology stuff (so it's more in line with its name). So moving forward, I will probably remove the easystast-flag from psycho (for the next version) and continue the psych stuff there, because currently easystats is quite field-agnostic (i.e., not only for psychologists), so there's nowhere specific functions like SDT measures would really fit ☺️

**Comment by marco2gandolfo** [comment]
Nice! Makes sense to me.
Thanks for clarifying and to both for your quick reply.

Cheers,
Marco
